### PR TITLE
Implement reset strategies

### PR DESCRIPTION
**Pull request by jessebraham**
As usual this is taken from `esptool.py`, which can be seen [here](https://github.com/espressif/esptool/blob/f37f38433786f73d8a8274b146859ac9955ac1e7/esptool/reset.py).

I have not yet done much testing, but I have at least confirmed I can flash every supported device from macOS. This will need to be tested on Linux and Windows as well, and should probably be tested more thoroughly on macOS too.

Not super excited about bumping the MSRV so high, but it's probably not the end of the world. By the time we have a stable release it there should be at least one new release. If we can get around the need for `AsRawFd` then the bump won't be necessary, bump I'm not sure how to do that currently (or if it's even possible).

### CODE REVIEW

**Comment by liebman** [comment]
I still get this:
```
espflash write-bin -b 921600 -p /dev/tty.usbserial-14644301 0x3b0000 ../target/spiffs.img
[2023-01-17T20:13:12Z INFO ] Serial port: '/dev/tty.usbserial-14644301'
[2023-01-17T20:13:12Z INFO ] Connecting...
[2023-01-17T20:13:13Z INFO ] Using flash stub
[2023-01-17T20:13:14Z WARN ] Setting baud rate higher than 115,200 can cause issues
[2023-01-17T20:13:14Z INFO ] Serial port: '/dev/tty.usbserial-14644301'
[2023-01-17T20:13:14Z INFO ] Connecting...
Error: espflash::serial_error

  × Failed to open serial port /dev/tty.usbserial-14644301
  ├─▶ Failed to open serial port /dev/tty.usbserial-14644301
  ├─▶ Error while connecting to device
  ├─▶ IO error while using serial port: Device or resource busy
  ╰─▶ Device or resource busy
```

**Review by MabezDev — APPROVED** [review]
LGTM, I never really have any issue flashing in general (across multiple boards, interfaces, os'), but one instance where I do see it is when I get the board in a state where it resets immediately in ROM. esptool.py can usually recover (most likely due to the tighter timings) where as espflash will either fail or take a few tries. This should help with that.

**Review by SergioGasquez — APPROVED** [review]
LGTM! Just a quick, and maybe nonsense, question: I assume the order of `set_dtr` and `set_rts` is relevant, that's why we have 2 methods, but why can we have a `set_dtr_rts` method for  UNIX and not a general one?

**Comment by jessebraham** [comment]
@SergioGasquez that method sets DTR and RTS _simultaneously_ rather than sequentially using syscalls, which are only available on UNIX.

**Comment by Andrew-Collins** [comment]
Didn't work for me through `espressif/idf-rust:all_1.66.0.0`.

But then I ported over my patch from #323

```diff
diff --git a/espflash/src/connection/reset.rs b/espflash/src/connection/reset.rs
index 4304dda..975029a 100644
--- a/espflash/src/connection/reset.rs
+++ b/espflash/src/connection/reset.rs
@@ -95,6 +95,12 @@ impl ResetStrategy for ClassicReset {
             self.delay
         );
 
+        self.set_dtr(interface, false)?;
+        self.set_rts(interface, false)?;
+
+        self.set_dtr(interface, true)?;
+        self.set_rts(interface, true)?;
+
         self.set_dtr(interface, false)?; // IO0 = HIGH
         self.set_rts(interface, true)?; // EN = LOW, chip in reset
 
@@ -106,6 +112,7 @@ impl ResetStrategy for ClassicReset {
         sleep(Duration::from_millis(self.delay));
 
         self.set_dtr(interface, false)?; // IO0 = HIGH, done
+        self.set_rts(interface, false)?;
 
         Ok(())
     }
```
And it worked

```
[2023-02-01T06:40:52Z DEBUG] BoardInfo(
        ConnectArgs {
            baud: None,
            port: None,
            no_stub: false,
        },
    )
[2023-02-01T06:40:52Z DEBUG] connecting to crates.io:443 at 13.35.138.24:443
[2023-02-01T06:40:52Z DEBUG] No cached session for DnsName(DnsName(DnsName("crates.io")))
[2023-02-01T06:40:52Z DEBUG] Not resuming any session
[2023-02-01T06:40:52Z DEBUG] Using ciphersuite TLS13_AES_128_GCM_SHA256
[2023-02-01T06:40:52Z DEBUG] Not resuming
[2023-02-01T06:40:52Z DEBUG] TLS1.3 encrypted extensions: [ServerNameAck]
[2023-02-01T06:40:52Z DEBUG] ALPN protocol is None
[2023-02-01T06:40:52Z DEBUG] created stream: Stream(RustlsStream)
[2023-02-01T06:40:52Z DEBUG] sending request GET https://crates.io/api/v1/crates/espflash/versions
[2023-02-01T06:40:52Z DEBUG] writing prelude: GET /api/v1/crates/espflash/versions HTTP/1.1
    Host: crates.io
    User-Agent: ureq/2.6.1
    Accept: */*
    accept-encoding: gzip
[2023-02-01T06:40:52Z DEBUG] Ticket saved
[2023-02-01T06:40:53Z DEBUG] Chunked body in response
[2023-02-01T06:40:53Z DEBUG] response 200 to GET https://crates.io/api/v1/crates/espflash/versions
[2023-02-01T06:40:53Z DEBUG] adding stream to pool: https|crates.io|443 -> Stream(RustlsStream)
[2023-02-01T06:40:53Z INFO ] Detected 3 serial ports
[2023-02-01T06:40:53Z INFO ] Ports which match a known common dev board are highlighted
[2023-02-01T06:40:53Z INFO ] Please select a port
[2023-02-01T06:40:54Z INFO ] Serial port: '/dev/ttyACM0'
[2023-02-01T06:40:54Z INFO ] Connecting...
[2023-02-01T06:40:54Z DEBUG] Matched `SerialPortType::PciPort or ::Unknown`
[2023-02-01T06:40:54Z DEBUG] Using UnixTight reset strategy with delay of 50ms
[2023-02-01T06:40:54Z DEBUG] Using UnixTight reset strategy with delay of 550ms
[2023-02-01T06:40:54Z DEBUG] Using Classic reset strategy with delay of 50ms
[2023-02-01T06:40:54Z INFO ] Using flash stub
[2023-02-01T06:40:54Z DEBUG] Loading flash stub for chip: Esp32s3
[2023-02-01T06:40:54Z DEBUG] Write 4836 byte stub text
[2023-02-01T06:40:54Z DEBUG] Write 4 byte stub data
[2023-02-01T06:40:54Z DEBUG] Finish stub write
[2023-02-01T06:40:54Z DEBUG] Stub written!
[2023-02-01T06:40:54Z DEBUG] Re-detected chip: Esp32s3
[2023-02-01T06:40:54Z DEBUG] Attempting flash enable with: SpiAttachParams { clk: 0, q: 0, d: 0, hd: 0, cs: 0 }
[2023-02-01T06:40:54Z DEBUG] Flash detect OK!
Chip type:         esp32s3 (revision v0.1)
Crystal frequency: 40MHz
Flash size:        8MB
Features:          WiFi, BLE
MAC address:       f4:12:fa:4f:29:e0
```

Tested on an esp32 board I have too, but in neither case did `UnixTight` rest succeed.

**Comment by MabezDev** [comment]
FYI esptool recently added this commit https://github.com/espressif/esptool/commit/fc998f6bc9eaa6dc20cc48fdb3d318ec1638cf51 - which might be relevant to this PR.

**Comment by jessebraham** [comment]
Thanks for pointing that out @MabezDev, looks like I probably missed that commit by a single day 😁 I've added that final line, and also upon reviewing the reset strategies noticed one additional typo in the `UnixTightReset` strategy.

**Comment by Andrew-Collins** [comment]
Still no dice using `UnixTightReset` for the esp32 on my end
```
2023-02-01T23:00:21Z INFO ] Please select a port
[2023-02-01T23:00:22Z INFO ] Serial port: '/dev/ttyUSB0'
[2023-02-01T23:00:22Z INFO ] Connecting...
[2023-02-01T23:00:22Z DEBUG] Using UnixTight reset strategy with delay of 50ms
[2023-02-01T23:00:22Z DEBUG] Using UnixTight reset strategy with delay of 550ms
[2023-02-01T23:00:22Z DEBUG] Using Classic reset strategy with delay of 50ms
[2023-02-01T23:00:23Z INFO ] Using flash stub
[2023-02-01T23:00:23Z DEBUG] Loading flash stub for chip: Esp32
```

**Comment by MabezDev** [comment]
@Andrew-Collins in https://github.com/esp-rs/espflash/issues/323#issuecomment-1412913424 you mention you are passing the USB device to a (docker?) container, have you tried flashing the board directly from your host machine? Just to try and rule out container issues.

**Comment by Andrew-Collins** [comment]
`UnixTightReset` behaviour is the same on host and conatiner, and with 4 different esp32 boards.

But the S3 specific issue I was having was actually due to the container, see my comment on #323 if you are interested:
https://github.com/esp-rs/espflash/issues/323#issuecomment-1412913424

**Comment by Andrew-Collins** [comment]
If `UnixTightReset` gets going I'll test the S3 in my original container to see what happens, as it could be useful as a fallback option for JTAG-Serial ports.

**Review by JurajSadel — CHANGES_REQUESTED** [review]
I tried it on Windows and I got the build error:
```rust
Compiling espflash v2.0.0-rc.3 (C:\Users\JurajSadel\.cargo\git\checkouts\espflash-0ea4e6814a65277e\3c0f9de\espflash)
error[E0433]: failed to resolve: use of undeclared type `UnixTightReset`
   --> espflash\src\connection\reset.rs:205:22
    |
205 |             Box::new(UnixTightReset::new(false)),
    |                      ^^^^^^^^^^^^^^ use of undeclared type `UnixTightReset`

error[E0433]: failed to resolve: use of undeclared type `UnixTightReset`
   --> espflash\src\connection\reset.rs:206:22
    |
206 |             Box::new(UnixTightReset::new(true)),
    |                      ^^^^^^^^^^^^^^ use of undeclared type `UnixTightReset`

warning: unused import: `USB_SERIAL_JTAG_PID`
  --> espflash\src\targets\flash_target\esp32.rs:11:30
   |
11 |     connection::{Connection, USB_SERIAL_JTAG_PID},
   |                              ^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default
   ```

**Pull request closed without merging**
