### PR TITLE
Use `esp-flasher-stub` stubs

### PR DESCRIPTION
**Pull request by SergioGasquez**
- Replace the current C stubs for `esp-flasher-stub` generated stubs.
  - `esp-flasher-stub` does not generate ESP8266 stubs so I kept the C based stub for it

### CODE REVIEW

**Comment by MabezDev** [comment]
Given how untested the stubs are, this has the potential to induce a bunch of bug reports. Do we want to add them behind a flag first?

**Comment by SergioGasquez** [comment]
> Given how untested the stubs are, this has the potential to induce a bunch of bug reports. Do we want to add them behind a flag first?

I initially did that, but as Jesse suggested, not sure how many people will test it if it's behind a feature. Happy to revert the lats commit and keep it behind a flag, though.

**Comment by MabezDev** [comment]
> I initially did that, but as Jesse suggested, not sure how many people will test it if it's behind a feature

True, presumably there will be a rc release for espflash 3.0, so I guess if many people run into issues with the rc we can revisit the decision.

**Review by MabezDev — APPROVED** [review]

**Review by jessebraham — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
