### PR TITLE
Turn off some dependencies for library users

### PR DESCRIPTION
**Pull request by bugadani**
In this PR I hide some code behind the `serialport` feature. The code was otherwise available, but not really useful without the feature. Additionally, I'm making certain dependencies optional that were only used with either cli or serialport only. Lastly, I'm moving some code (chiefly `ProgressCallbacks` [defined together with `FlashTarget`] and `checksum` [only used in one place]) to new locations where I believe they better belong.

### CODE REVIEW

**Comment by bugadani** [comment]
I'm going to assume that the apple error (`error: failed to run custom build command for openssl-sys v0.9.101`) is not my fault :)

**Comment by SergioGasquez** [comment]
> I'm going to assume that the apple error (`error: failed to run custom build command for openssl-sys v0.9.101`) is not my fault :)

Feel free to ignore it, see https://github.com/esp-rs/espflash/issues/597, it should now be fixed though. Thanks for the PR, will review it on Monday!

**Comment by NobodyXu** [comment]
cc 1.0.88 should fix this

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks for this polishing PR!

**Pull request merged**
