### PR TITLE
Add basic serial monitor

### PR DESCRIPTION
**Pull request by icewind1991**
Adds a basic `--monitor` option to open a serial monitor after flashing is completed

### CODE REVIEW

**Review by MabezDev — APPROVED** [review]
After addressing the issue `clippy` spotted, this is all good I think!

**Comment by jessebraham** [comment]
This seems to work fine on my Mac, however it will not build on Windows for me. I believe `termion` is the culprit, output can be found in [this gist](https://gist.github.com/jessebraham/1fa4f24b33ea073059024651fb88ac48). It's possible that it's an issue with my system, but is somebody else able to confirm?

**Comment by icewind1991** [comment]
switched to crossterm for doing the terminal handling which does work under windows

**Comment by jessebraham** [comment]
I'm unfortunately still having issues on Windows :(

```
PS C:\Users\Jesse Braham\Documents\Sandbox\esp32c3-experiments> cargo espflash --monitor COM3
   Compiling esp32c3 v0.1.0 (C:\Users\Jesse Braham\Documents\Sandbox\esp32c3-experiments)
    Finished dev [unoptimized + debuginfo] target(s) in 0.74s
Serial port: COM3
Connecting...

[00:00:01] ########################################      12/12      segment 0x0
[00:00:00] ########################################       1/1       segment 0x8000
[00:00:01] ########################################      13/13      segment 0x10000
Commands:
    CTRL+R    Reset chip
    CTRL+C    Exit

Error: Windows stdio in console mode does not support writing non-UTF-8 byte sequences
```

**Comment by icewind1991** [comment]
Can't reproduce:

image

**Comment by jessebraham** [comment]
Okay, if it's working for you then it's likely that the issue lies with my installation. I recall having changed the default PowerShell encoding at some point so that may have something to do with it. Thank you for checking.

**Review by jessebraham — APPROVED** [review]

**Comment by icewind1991** [comment]
@jessebraham can you see if the latest commit changes anything for you?

**Comment by jessebraham** [comment]
That seems to have fixed it, thanks!

**Pull request merged**
