### PR TITLE
Use clap instead of pico-args for cargo-espflash

### PR DESCRIPTION
**Pull request by jessebraham**
I've been wanting to do this for awhile and finally got around to it. While part of the reason was purely personal preference, this also (IMO) makes it easier for us to add options, performs better validation of command-line arguments, and doesn't require manual updates of the argument parsing function and help messages.

As a note, I did remove the `--chip` option as it was not actually being used (we perform auto-detection). I am fine with adding it back for compatibility reasons, but I personally don't see the need.

### CODE REVIEW

**Comment by N3xed** [comment]
Why not [`structopt`](https://crates.io/crates/structopt), I think that would make it more readable. But that's just my opinion.

**Review by MabezDev — APPROVED** [review]
I agree that structopt is nice! However either is a big improvement over picoargs, so either works for me :)

**Comment by jessebraham** [comment]
I would rather focus my efforts on other functionality at this point. Anybody is of course welcome to make further changes on top of mine, I just don't feel strongly enough either way to justify spending any more time on this.

**Comment by N3xed** [comment]
> I would rather focus my efforts on other functionality at this point. Anybody is of course welcome to make further changes on top of mine, I just don't feel strongly enough either way to justify spending any more time on this.

All good, was just a suggestion (I just like `structopt` :D).

**Review by icewind1991 — APPROVED** [review]

**Pull request merged**
