### PR TITLE
Read metadata from specified package when in a workspace

### LINKED ISSUE #291: can't specify partition table in a workspace
In a cargo workspace like:

```
[workspace]
resolver = "2"
members = [
    "thing",
    "some-other-thing",
]
```

Where `thing` has 

```
[package.metadata.espflash]
partition_table = "partitions.csv"
```

The default partition table is used instead of the specified one. Looks like only the workspace  `Cargo.toml` is parsed leaving no place to declare a custom partition file. Ideally this should detect the workspace and load the `Cargo.toml` from the specific crate being processed.

### PR DESCRIPTION
**Pull request by jessebraham**
Closes #291

### CODE REVIEW

**Comment by jessebraham** [comment]
@liebman Does this seem reasonable and work for your use case?

**Comment by liebman** [comment]
This gives me an error:
```
➜ cargo espflash flash --package candle --monitor -b 921600 -p /dev/tty.usbmodem14644301
Error: cargo_espflash::no_project

  × No Cargo.toml found in the current directory
  help: Ensure that you're running the command from within a cargo project
```
and if I run from the package directory:
```
➜ cargo espflash flash --monitor -b 921600 -p /dev/tty.usbmodem14644301 
Error: 
  × Failed to parse Cargo.toml
  ╰─▶ value from workspace hasn't been set
```

Cargo build does this just fine:
```
➜ cargo build --package candle
   Compiling candle v0.1.0 (/Users/chris.l/Dropbox/git/cat-mouse/crates/candle)
   Compiling esp-idf-ws2812 v0.1.0 (/Users/chris.l/Dropbox/git/cat-mouse/crates/esp-idf-ws2812)
    Finished dev [optimized + debuginfo] target(s) in 15.63s
```

**Comment by liebman** [comment]
I found this parses the entire workspace and gives you package names and paths (and a ton of un-needed info in this case).
```
use cargo::core::Workspace;
use cargo::util::Config;
use std::env;
use std::fs;

fn main() {
    let args: Vec<String> = env::args().collect();

    for p in &args[1..] {
        let path = fs::canonicalize(p).unwrap();
        let config = Config::default().unwrap();
        let ws = Workspace::new(path.as_path(), &config).unwrap();
        print!("{:#?}", ws);
    }
}
```

**Comment by jessebraham** [comment]
@liebman sorry forgot to comment when I closed this, I'm working on a (much better) version using `cargo`, it never even occurred to me to use it as a dependency (though it's obvious now) 😁 Thanks for the pointer!

**Pull request closed without merging**
